services:
  _defaults:
    autowire: true
    autoconfigure: true
  OmgFinally\SymfonyValidationConstraints\:
    resource: '../src/'
  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
